package org.codingmatters.poom.paged.collection.generation.generators.source.test;

import org.codingmatters.poom.paged.collection.generation.spec.Action;
import org.codingmatters.poom.paged.collection.generation.spec.PagedCollectionDescriptor;
import org.codingmatters.poom.paged.collection.generation.spec.pagedcollectiondescriptor.Types;
import org.generated.api.ValueList;
import org.generated.api.*;
import org.generated.api.types.Error;
import org.generated.api.types.*;

public interface TestData {
    PagedCollectionDescriptor FULL_COLLECTION = PagedCollectionDescriptor.builder()
            .name("NoParams").entityIdParam("entity-id")
            .types(Types.builder()
                    .entity(org.generated.api.types.Entity.class.getName())
                    .create(Create.class.getName())
                    .batchCreateResponse(BatchCreateResponse.class.getName())
                    .replace(Replace.class.getName())
                    .update(Update.class.getName())
                    .error(Error.class.getName())
                    .message(Message.class.getName())
                    .valueList(ValueList.class.getName())
                    .build())
            .browse(Action.builder()
                    .requestValueObject(NoParamsGetRequest.class.getName())
                    .responseValueObject(NoParamsGetResponse.class.getName())
                    .build())
            .create(Action.builder()
                    .requestValueObject(NoParamsPostRequest.class.getName())
                    .responseValueObject(NoParamsPostResponse.class.getName())
                    .build())
            .batchCreate(Action.builder()
                    .requestValueObject(NoParamsBatchPostRequest.class.getName())
                    .responseValueObject(NoParamsBatchPostResponse.class.getName())
                    .build())
            .retrieve(Action.builder()
                    .requestValueObject(NoParamsElementGetRequest.class.getName())
                    .responseValueObject(NoParamsElementGetResponse.class.getName())
                    .build())
            .delete(Action.builder()
                    .requestValueObject(NoParamsElementDeleteRequest.class.getName())
                    .responseValueObject(NoParamsElementDeleteResponse.class.getName())
                    .build())
            .replace(Action.builder()
                    .requestValueObject(NoParamsElementPutRequest.class.getName())
                    .responseValueObject(NoParamsElementPutResponse.class.getName())
                    .build())
            .update(Action.builder()
                    .requestValueObject(NoParamsElementPatchRequest.class.getName())
                    .responseValueObject(NoParamsElementPatchResponse.class.getName())
                    .build())
            .build();

    PagedCollectionDescriptor NO_COLLECTION_COLLECTION = PagedCollectionDescriptor.builder()
            .name("NoCollection").entityIdParam(null)
            .types(Types.builder()
                    .entity(org.generated.api.types.Entity.class.getName())
                    .create(null)
                    .replace(Replace.class.getName())
                    .update(Update.class.getName())
                    .error(Error.class.getName())
                    .message(Message.class.getName())
                    .valueList(ValueList.class.getName())
                    .build())
            .browse((Action) null)
            .create((Action) null)
            .retrieve(Action.builder()
                    .requestValueObject(NoCollectionGetRequest.class.getName())
                    .responseValueObject(NoCollectionGetResponse.class.getName())
                    .build())
            .delete(Action.builder()
                    .requestValueObject(NoCollectionDeleteRequest.class.getName())
                    .responseValueObject(NoCollectionDeleteResponse.class.getName())
                    .build())
            .replace(Action.builder()
                    .requestValueObject(NoCollectionPutRequest.class.getName())
                    .responseValueObject(NoCollectionPutResponse.class.getName())
                    .build())
            .update(Action.builder()
                    .requestValueObject(NoCollectionPatchRequest.class.getName())
                    .responseValueObject(NoCollectionPatchResponse.class.getName())
                    .build())
            .build();
}
