---
stages:
  - name: prepare-env
    exec:
      - docker pull $CI_TOOLS_IMAGE
      - mkdir -p $WORKSPACE/.m2

  - name: build
    exec:
      - $MVN clean install

  - name: deploy
    exec:
      - $MVN deploy -DskipTests

onSuccess:
  - name: notify-flexio
    exec:
      - curl -XGET 'https://my.flexio.io/channelApi/flexHttpInOut/59d3a0105d443519843d0496/5adf40aededdbb452368cfca?repository=poom-services&status=0'


onError:
  - name: notify-flexio
    exec:
      - curl -XGET 'https://my.flexio.io/channelApi/flexHttpInOut/59d3a0105d443519843d0496/5adf40aededdbb452368cfca?repository=poom-services&status=1'



env:
  - SETTING_FILE: /home/nel/.m2/settings.xml
  - CI_TOOLS_IMAGE: localhost:5000/poom-ci/ci-tools:0.0.1-SNAPSHOT
  - MVN: docker run --rm -v $SRC:/src -v $WORKSPACE/.m2:/root/.m2 -v $SETTING_FILE:/root/.m2/settings.xml $CI_TOOLS_IMAGE mvn -B