---
stages:
  - name: build
    exec:
      - $MVN clean install
#  - name: deploy
#    exec:
#      - $MVN deploy

onSuccess:
  - name: notify-flexio
    exec:
      - curl -XGET 'https://my.flexio.io/channelApi/flexHttpInOut/59d3a0105d443519843d0496/5adf40aededdbb452368cfca?repository=poom-services&status=0'


onError:
  - name: notify-flexio
    exec:
      - curl -XGET 'https://my.flexio.io/channelApi/flexHttpInOut/59d3a0105d443519843d0496/5adf40aededdbb452368cfca?repository=poom-services&status=1'



env:
  MVN: docker run -it --rm -v $SRC:/src -v $WORKSPACE/.m2:/root/.m2 flexio-build-java mvn