---
stages:
  - name: build
    exec:
      - mvn clean install

  - name: notify-flexio
    exec:
      - curl -XGET 'https://my.flexio.io/channelApi/flexHttpInOut/59d3a0105d443519843d0496/5adf40aededdbb452368cfca?repository=poom-services&status=0'


