---
pipeline:
  $conforms-to: [org.codingmatters.poom.ci.pipeline.StageProvider]
  stages:
    $list: $stage

  onSuccess:
    $list: $stage
  onError:
    $list: $stage

  env:
    $value-object: org.codingmatters.value.objects.values.ObjectValue



stage:
  name: string
  timeout: long
  exec:
    $list: string

stageHolder:
  stage: $stage
  type:
    $enum: MAIN, ERROR, SUCCESS