#%RAML 1.0
title: api registry
version: v2
description: Poor man's API registry
baseUri: https://api.codingmatters.org/api/registry
mediaType: application/json

annotationTypes: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/annotation-types/codingmatters.raml

/apis:
  displayName: apis
  (paged-collection):
  get:
    is: [rfc7233Browsing: {entityType: ApiSpec, error: Error}]
  /{api}:
    displayName: an api
    (paged-collection-entity):
    uriParameters:
      api: string
    get:
      is: [entityRetrieve: {entityType: ApiSpec, error: Error}]

types:
  Message: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/types/message.raml
  Error: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/types/error-with-messages.raml

  ApiSpec:
    type: object
    properties:
      name: string
      endpoint: string
      version: string
      protocols:
        type: array
        items:
          enum: [http, http2]


traits:
  rfc7233Browsing: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/traits/collection/rfc7233-browse-collection.raml
  entityCreation: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/traits/collection/create.raml
  entityRetrieve: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/traits/entity/retrieve.raml
  entityReplace: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/traits/entity/replace.raml
  entityUpdate: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/traits/entity/update.raml
  entityDelete: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.27.0/apis/core/traits/entity/delete.raml