version: '3'

services:

  github-webhook:
    image: ${github-webhook.image}
    ports:
      - 6543:9999
    environment:
      GITHUB_SECRET_TOKEN: 9a167bbea7e96c86fd87ae254f646cbea050ef63
      PIPELINE_API_URL: http://pipeline-service:9999/pipelines/v1

  pipeline-service:
    image: ${pipeline-service.image}
    environment:
      JOB_REGISTRY_URL: http://poomjobs-registries-service:9999/poomjobs-jobs/v1
    ports:
      - 6545:9999

  poomjobs-registries-service:
    image: ${poomjobs-registries-service.image}
    ports:
      - 6544:9999

  maven-repository:
    image: ${docker.registry}/${docker.namespace}/archiva:${archiva.version}
    ports:
      - 8080:8080
    volumes:
      - archiva-conf:/var/archiva/conf
      - archiva-data:/var/archiva/data
      - archiva-logs:/var/archiva/logs
      - archiva-repositories:/var/archiva/repositories

volumes:
  archiva-conf:
  archiva-data:
  archiva-logs:
  archiva-repositories:


