#%RAML 1.0
title: Generic Resource
version: v2
description: Generic Resource
baseUri: https://api.codingmatters.org/ui/resource
mediaType: application/json

annotationTypes:
  value-object-hint:
    type: string[]
  conforms-to:
    type: string[]
  already-defined:
    type: string
  object-impl:
    enum: [ Val, ObjectValue ]

/:
  displayName: paged collection
  type: {pagedCollection: {entityType: object, entityCreationType: object}}
  /{entity-id}:
    displayName: entity
    type: {entity: {entityType: object, entityReplaceType: object, entityUpdateType: object}}


types:
  Message:
    type: object
    properties:
      key: string
      args:
        type: array
        items: string

  Error:
    type: object
    properties:
      token: string
      code:
        enum: [
          ILLEGAL_RANGE_SPEC,
          UNEXPECTED_ERROR,
          OVERLOADED,
          RESOURCE_NOT_FOUND,
          ILLEGAL_RESOURCE_CREATION,
          ILLEGAL_RESOURCE_CHANGE,
          INVALID_OBJECT_FOR_CREATION,
          INVALID_OBJECT_FOR_REPLACEMENT,
          INVALID_OBJECT_FOR_UPDATE,
          ENTITY_CREATION_NOT_ALLOWED,
          ENTITY_REPLACEMENT_NOT_ALLOWED,
          ENTITY_UPDATE_NOT_ALLOWED,
          INVALID_ACCOUNT,
          BAD_REQUEST]
      messages:
        type: array
        items: Message


resourceTypes:
  pagedCollection:
    usage: used to implement a paged collection
    description: |
      A paged collection of <<entityType>>.
      The GET method enables to paginate over <<entityType>> entities while conforming to RFC 7233 paging.
      The POST method enables to create <<entityType>> by providing a <<entityCreationType>> as body.
    get:
      description: |
        RFC 7233 paged collection of arbitrary objects.
        Filtering and ordering are optional features.
      headers:
        range:
          type: string
          required: false
      queryParameters:
        filter:
           type: string
           description: |
              Conforms to PropertyFilter grammar from poom-services-org.codingmatters.poom.generic.resource.domain.
              Dotted properties are supported for nested objects.
              Supported properties are left to the implementation.
        order-by:
           type: string
           description: |
              Confirms to PropertySort grammar from poom-services-org.codingmatters.poom.generic.resource.domain.
              Dotted properties are supported for nested objects.
              Supported properties are left to the implementation.
      responses:
        200:
          description: |
            complete list or last elements of the list
          headers:
            Content-Range: string
            Accept-Range: string
          body: <<entityType>>[]
        206:
          description: |
            partial list
          headers:
            Content-Range: string
            Accept-Range: string
          body: <<entityType>>[]
        416:
          description: |
            the specified range is not acceptable (Error code is ILLEGAL_RANGE_SPEC).
          headers:
            Content-Range: string
            Accept-Range: string
          body: Error
        400:
          description: |
            the query is not acceptable (Error code is ILLEGAL_REQUEST).
          body: Error
        404:
          description: |
            No paged resource found. Code RESOURCE_NOT_FOUND.
          body: Error
        500:
          description: UNEXPECTED_ERROR.
          body: Error
    post:
      description: |
        creates an entity from an object validated agains the config form dialog
      body: object
      responses:
        201:
          headers:
            x-entity-id: string
            location: string
          body: <<entityCreationType>>
        400:
          body: Error
        401:
          body: Error
        403:
          body: Error
        404:
          body: Error
        405:
          body: Error
        500:
          body: Error

  entity:
    uriParameters:
      entity-id: string
    get:
      description: |
        gets a <<entityType>> entity
      responses:
        200:
          headers:
            x-entity-id: string
            location: string
          body: <<entityType>>
        400:
          body: Error
        401:
          body: Error
        403:
          body: Error
        404:
          body: Error
        500:
          body: Error

    put:
      description: |
        replaces a <<entityType>> entity given the <<entityReplaceType>> body
      body: <<entityReplaceType>>
      responses:
        200:
          headers:
            x-entity-id: string
            location: string
          body: <<entityType>>
        400:
          body: Error
        401:
          body: Error
        403:
          body: Error
        404:
          body: Error
        405:
          body: Error
        500:
          body: Error
    patch:
      description: |
        partially updates a <<entityType>> entity given the <<entityUpdateType>> body
      body: <<entityUpdateType>>
      responses:
        200:
          headers:
            x-entity-id: string
            location: string
          body: <<entityType>>
        400:
          body: Error
        401:
          body: Error
        403:
          body: Error
        404:
          body: Error
        405:
          body: Error
        500:
          body: Error
    delete:
      description: deletes an entity
      responses:
        204:
          description: resource deleted
        400:
          body: Error
        401:
          body: Error
        403:
          body: Error
        404:
          body: Error
        500:
          body: Error
