#%RAML 1.0
title: Fragment
version: 1
baseUri: https://api.codingmatters.org/fragment
mediaType: application/json

annotationTypes: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.35.0/apis/core/annotation-types/codingmatters.raml

types:
  Message: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.35.0/apis/core/types/message.raml
  Error: !include https://raw.githubusercontent.com/flexiooss/poom-api-specs/1.35.0/apis/core/types/error-with-messages.raml